# Generated by Django 3.2.11 on 2022-01-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
