# Generated by Django 3.2.11 on 2022-01-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_link_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
