# Generated by Django 3.2.11 on 2022-02-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_project',
            field=models.BooleanField(default=True),
        ),
    ]
